### ISSUE TITLE
Question : main layout

### ISSUE THREAD

**Issue by daufinsyd** [Sw24Softwares/StarkeVerben#13]
I found a little strange that the 3rd person is not right after infinitive but below participle.
Is there any particular reason ? (I first learnt 3rd person before preterit/participle however I'm not German)

**Comment by Swarthon** [comment]
We are not German neither. In fact, this is the way we learn the verbs. But it could be an interesting feature to allow the users to customize the layout.

**Comment by Swarthon** [comment]
Hi @daufinsyd, I know it's been a while but we had other plans and I wasn't so much inspired. But now, this is it ! This feature should be available in the next release.

**Comment by daufinsyd** [comment]
Thank you ! :)
