### ISSUE TITLE
Starke Verban app gets crashed.

### ISSUE THREAD

**Issue by Sammaz2** [Sw24Softwares/StarkeVerben#16]
### Actual behavior
I opened the starke verban opensource android app. After that I clicked on the list option present on the bottom right corner. After that I started searching by typing a word in the blank. And then I rotated my phone. Suddenly the app crashed.

#### How to reproduce

* First you need to download the app from fdroid and then install it. After that open the app.

* Click on the list option present on the bottom right corner of the page.

* Click on the search blank. And then type a word. And search it. 

* Rotate your phone, suddenly the app will crash.

https://youtu.be/eBt9ut-jBis 

* Browser: Starke Verban

* Version:3.1.0

* Operating system:7.1.2

* Device model:Redmi 4

**Comment by 24PaH** [comment]
First of all, thank you for this kind contribution and your precise description of the bug.

We have noticed that there are some strange behaviours on screen rotate, but we will try to fix this for the next release.
