### ISSUE TITLE
Need new logo?

### ISSUE THREAD

**Issue by anaufalm** [Sw24Softwares/StarkeVerben#17]
Hi, Im freelance graphic designer.

I just look at your application, and unfortunately I do not see the identity in the logo and less interesting. I want to contribute to your project. I can create a new logo for your app. What do you think? :)

Rgrd,
Naufal

[My Recent portfolio](https://www.instagram.com/faal.id/)

**Comment by 24PaH** [comment]
Hello Ahmad, your work is quite amazing, that is why we would be very happy to have a great new logo from your design. We just have one question: what kind of license do you apply on your images? Regarding the 'specifications', we would like to keep that orange color, and that the logo stays clear and somehow universal. Thank you for your kind interest in our project!

**Comment by anaufalm** [comment]
CC BY maybe? What do you think?

**Comment by 24PaH** [comment]
Yeah sure

**Comment by naufaldsg** [comment]
Hi @24PaH , this is me @anaufalm, I just want to inform you that I lost my account few weeks ago, so sad and I use this account for now, thank you. And sorry just responding to your message now, I was very busy last month with my studies. And now I can focus on contributing.

About your logo, I will make it asap, please wait. :)

**Comment by 24PaH** [comment]
Hello Naufal,
glad to see that you are still interested for this contribution. Don't worry about the time it will take, studies are more important, we will wait :-)

**Comment by naufaldsg** [comment]
Hi @24PaH , sorry for waiting, this is logo for you. What do you think?

![sv](https://user-images.githubusercontent.com/44208945/49926994-84981b80-feef-11e8-8916-844ad0bd9d1e.png)

Wich one do you prefer? A, B, C, or D?

**Comment by 24PaH** [comment]
Wow, that is absolutely beautiful. Thank you very much! No problem concerning the waiting.

We think that the better would be the A, especially for the meaning.
Thank you one more time.

**Comment by naufaldsg** [comment]
Okaay, so there is no suggest/input so far? What about the colors, size requirement, or etc? If we have done for this, I will send all files that you need to you :)

**Comment by 24PaH** [comment]
In fact, we thought about how will it look like if we even the begining of the 'S' letter and the end of the book, just like that.
 ![](https://i.imgur.com/WH1MFBs.jpg)

Maybe that the book will be better recognized and understood (but it is just an opinion).

**Comment by naufaldsg** [comment]
Yaa, sure. Actually I have tried that before, and it looks weird. Emm it looks like the E or F letter. So, I don't recommend it. What do you think?

![screenshot_432](https://user-images.githubusercontent.com/44208945/49958532-b20bb600-ff3d-11e8-8f9e-249270e5b2e6.png)
*I've tried many times btw to find the best :D

**Comment by 24PaH** [comment]
Yes you are right. 
What is (kinda) gained for the book is lost for the 'S'.

Okay so let us just go for the first one that you have proposed, it seems that it is the one that suits at best!

**Comment by naufaldsg** [comment]
Shukron ^^

So, what size do you need for the logo? or should I just make based on [material design](https://material.io/design/iconography/product-icons.html#specs)?

[This](https://drive.google.com/folderview?id=1OmONuN4BzeXMKkjXpoAJDAUgd8cpHKkt) is some example of logo size for android apps (playstore/f-droid).

**Comment by 24PaH** [comment]
I don't know, maybe just doing as said in material design guidelines will be sufficient

**Comment by 24PaH** [comment]
You can send me only scalables if you want, and I will bother with the sizes later

**Comment by naufaldsg** [comment]
Okay, I've upload the files on this [folder](https://drive.google.com/open?id=1wJKpbuq2-HZ5iOrs68YRJ6OCKVBRl7fS), could you check it? Is there more you want? Feel free to comment :)

Ah, about icon. which one will do you use?
![sv-icon](https://user-images.githubusercontent.com/44208945/50045976-9388f480-00ce-11e9-9b7a-04a0a19a6fed.png)

**Comment by 24PaH** [comment]
Everything is good concerning the folder, thank you one more time :D 

Well, don't worry about the icon(s), I thought about doing [adaptive ones](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive).
So I'll do these myself, the folder you shared contains everything needed.

**Comment by naufaldsg** [comment]
Ahh I see, you can use vector files on file folder for scalables, and u're welcome. ;)

I make [pr](https://github.com/Sw24Softwares/StarkeVerben/pull/20) to make your repo looks a little more attractive. Lets see that!

**Comment by 24PaH** [comment]
That's cool! Thanks!

**Comment by naufaldsg** [comment]
Ur welcome.

**Comment by naufaldsg** [comment]
Cant wait the new logo implemented on new release :D

**Comment by 24PaH** [comment]
Yeah, me too!

In fact, we thought about redesigning the application and releasing the fresh new icon with it, so it will maybe take little time.
