### ISSUE TITLE
Additional translations

### ISSUE THREAD

**Issue by matmai** [Sw24Softwares/StarkeVerben#2]
Would be great to add more translations beside french to make the app more usefull for more people.

**Comment by 24PaH** [comment]
Yes, we have planned that in the middle of the development, that is why it is not implemented yet. We will probably do that soon, but feel free to contribute when you have an idea.

**Comment by Swarthon** [comment]
The translation system is here ! You can now add your translations file. We hope that you like the app. Please create more issue if you have any ideas. We are happy to see people interested in our work.

Fixed here : 219a3f38c59841b5e8df61ee540517835a978ae6
