### ISSUE TITLE
Overlapping content in the single lesson screen

### ISSUE THREAD

**Issue by ghost** [Sw24Softwares/StarkeVerben#8]
Right now the app looks ok in the portrait orientation. However, if you turn the phone in landscape there isn't sufficient space for all the UI elements so you end up with the content being cut off and the two buttons on top of the visible content.

As a simple fix the LinearLayout should be wrapped by a ScrollView so the user can scroll the content in the available space. Ideally, besides the ScrollView, there should be other changes to the layout itself or the dimensions used(for example, in landscape there's no point in setting the margin of the buttons to 45dp, it would just waste the space). A even better alternative would be to use another layout for the landscape configuration.

**Comment by Swarthon** [comment]
Thanks for your report, we will try to solve it in the next few days.

**Comment by ghost** [comment]
I can write a fix and submit another pull request, I just need to know if I should make the smallest change(just adding the ScrollView) or also change the layouts themselves.

**Comment by 24PaH** [comment]
You can, of course, change and PR what you want to. We will always be happy to see you or anyone else invested in our project!
I just want to know if you want only to improve the user experience in landscape mode, or if you want to rewrite the whole layout code (both cases are possible).
Thank you for your comprehension!
